services:
  richard_mariadb:
    image: mariadb:10.11.5
    container_name: richard_mariadb
    hostname: richard_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - "/opt/richard:/var/lib/mysql"
  richard_java:
    image: richard_java_img
    container_name: richard_java
    hostname: richard_java
    ports:
      - "8082:8081"
    depends_on:
      - richard_mariadb
